### ISSUE TITLE
Links for SLAMSeq documentation broken

### ISSUE THREAD

**Issue by slsevilla** [nf-core/slamseq#18]
**Describe the bug**
Multiple links within SLAMSeq documentation produce Error 404 messages.

**To Reproduce**
1. Go to [documentation page](https://nf-co.re/slamseq/1.0.0/docs/usage#optional-columns)
2. Scroll down to **Example design files have been provided in the test-datasets.**
3. Select **test-datasets**

1. Go to [documentation page](https://nf-co.re/slamseq/1.0.0/docs/usage#reference-genomes)
2. Scroll down to **You can find the keys to specify the genomes in the iGenomes config file. Common genomes that are supported are:**
3. Select **iGenomes config file**

**Expected behavior**
I was hoping to review input design examples I could reference.

**Browser:**
 - OS: iOS
 - Browser: chrome
- Version: 87.0.4280.88

**Comment by FranBonath** [comment]
Merging will depend on updates to the dependencies
